# Module Three Activity

You will complete your assignment code in this **Module_Three_Activity.ipynb** Notebook file from the filetree that is pre-templated for your modification in accordance with the assignment instructions.

Once your code is complete, you will download this notebook as an HTML file by clicking **File**, then **Download As**, then **HTML (.html)** from the Jupyter menu bar. You will also need to download the csv output file of your merged data. Validate that your code and outputs are rendered in the html file before submission.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Missing Blocks:</i></b> Ensure that you have clicked <b><mark>Run</mark></b> for all blocks before downloading as an HTML file or the block may be missing from your submission.</span>
</div>

### Data Source Information
The sourcing information for the data sets can be found in the `README.md` file within the data folder.

To use this starter code file, replace the `data/sample_use_only/{data_name}.csv` with the reference to your selected data from the list below:

- `data/nyc_temperatures.csv`
- `data/nyc_weather_2018.csv`
- `data/parsed.csv`
- `data/quakes.db`
- `data/tsunamis.csv`
- `data/weather.db`
- `data/weather_by_station.csv`
- `data/weather_stations.csv`

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>To Begin:</i></b> replace each <b>data_file_#</b> entry sample data path with the path to your selected data sets.</span>
</div>

If you choose to only use two data files instead of three, comment out the reference to data_file_3.

In [1]:
data_file_1 = "data/nyc_temperatures.csv"
data_file_2 = "data/nyc_weather_2018.csv"

## Installing Required Packages
If you have additional packages that you would like to use or install, add them to the **requirements.txt** file then run the next block.

In [2]:
!pip install --upgrade pip

Requirement already satisfied: pip in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (23.1.2)
Collecting pip
  Downloading pip-26.1.2-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 8.0 MB/s eta 0:00:00:00:010:01
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
Successfully installed pip-26.1.2

In [3]:
!pip install -r requirements.txt

Collecting ydata-profiling==4.16.1 (from -r requirements.txt (line 1))
  Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.7.1)
Collecting pydantic>=2 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (6.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.1.2)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.24.2)
Collecting htmlmin==0.1.12 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting phik<0.13,>=0.11.1 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading phik-0.12.5-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.24.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.30.0)
Collecting tqdm<5,>=4.48.2 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading tqdm-4.69.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.12.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Collecting statsmodels<1,>=0.13.2 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading statsmodels-0.14.6-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting typeguard<5,>=3 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading typeguard-4.6.0-py3-none-any.whl.metadata (3.7 kB)
Collecting imagehash==4.3.1 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Collecting wordcloud>=1.9.3 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading wordcloud-1.9.6-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting dacite>=1.8 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Collecting numba<=0.61,>=0.56.0 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading numba-0.61.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.8 kB)
Collecting PyWavelets (from imagehash==4.3.1->ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading pywavelets-1.9.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: pillow in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from imagehash==4.3.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.8.2)
Collecting llvmlite<0.45,>=0.44.0dev0 (from numba<=0.61,>=0.56.0->ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading llvmlite-0.44.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: pytz>=2020.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from phik<0.13,>=0.11.1->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (2023.5.7)
Collecting patsy>=0.5.6 (from statsmodels<1,>=0.13.2->ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting typing_extensions>=4.14.0 (from typeguard<5,>=3->ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: attrs>=19.3.0 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (23.1.0)
Collecting networkx>=2.4 (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Collecting annotated-types>=0.6.0 (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading pydantic_core-2.46.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic>=2->ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: six>=1.5 in /home/codio/.pyenv/versions/3.11.2/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling==4.16.1->-r requirements.txt (line 1)) (1.16.0)
Collecting numpy<2.2,>=1.16.0 (from ydata-profiling==4.16.1->-r requirements.txt (line 1))
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl (400 kB)
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading numba-0.61.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 28.5 MB/s  0:00:00
Downloading llvmlite-0.44.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 71.3 MB/s  0:00:006m0:00:0100:01
Downloading phik-0.12.5-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.0/679.0 kB 6.1 MB/s  0:00:00
Downloading statsmodels-0.14.6-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 45.6 MB/s  0:00:006m0:00:01
Downloading tqdm-4.69.1-py3-none-any.whl (675 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 675.5/675.5 kB 6.6 MB/s  0:00:00
Downloading typeguard-4.6.0-py3-none-any.whl (36 kB)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 18.4 MB/s  0:00:00
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading pydantic-2.13.4-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 19.4 MB/s  0:00:00
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Downloading wordcloud-1.9.6-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (551 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 551.3/551.3 kB 4.7 MB/s  0:00:00
Downloading puremagic-1.30-py3-none-any.whl (43 kB)
Downloading pywavelets-1.9.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 34.0 MB/s  0:00:00
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 47.6 MB/s  0:00:006m0:00:01
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (pyproject.toml) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27160 sha256=25e433cd5fd7bddd435e395ae2b455028136a7abfcb31a8e0d7d36dcabf93d63
  Stored in directory: /home/codio/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin
Installing collected packages: puremagic, htmlmin, typing_extensions, tqdm, numpy, networkx, multimethod, llvmlite, dacite, annotated-types, typing-inspection, typeguard, PyWavelets, pydantic-core, patsy, numba, visions, statsmodels, pydantic, imagehash, wordcloud, phik, ydata-profiling
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.5.0━━━━━━━━━━  2/23 [typing_extensions]
    Uninstalling typing_extensions-4.5.0:━━━━━━━━━━━━━━━━━━━━━  2/23 [typing_extensions]
      Successfully uninstalled typing_extensions-4.5.0━━━━━━━━━━━━  2/23 [typing_extensions]
  Attempting uninstall: numpy90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/23 [tqdm]g_extensions]
    Found existing installation: numpy 1.24.2━━━━━━━━━━━━━━━━━  3/23 [tqdm]
    Uninstalling numpy-1.24.2:90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/23 [numpy]
      Successfully uninstalled numpy-1.24.2━━━━━━━━━━━━━━━━━━━━━━━  4/23 [numpy]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23/23 [ydata-profiling] [ydata-profiling]
Successfully installed PyWavelets-1.9.0 annotated-types-0.8.0 dacite-1.9.2 htmlmin-0.1.12 imagehash-4.3.1 llvmlite-0.44.0 multimethod-1.12 networkx-3.6.1 numba-0.61.0 numpy-1.26.4 patsy-1.0.2 phik-0.12.5 puremagic-1.30 pydantic-2.13.4 pydantic-core-2.46.4 statsmodels-0.14.6 tqdm-4.69.1 typeguard-4.6.0 typing-inspection-0.4.2 typing_extensions-4.16.0 visions-0.8.1 wordcloud-1.9.6 ydata-profiling-4.16.1

## Import the Required Packages
If you have additional packages that you would like to import, add them here.

In [4]:
import pandas as pd
import numpy as np

## Loading and Preprocessing the Data
After you have selected your data set that wish to wrangle, replace the reference file path in the code block at the top of this Notebook, then run the following blocks.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you need to preprocess or clean your dataset before merging.</span>
</div>

### Data File 1 dataframe
Here we will load the data_file_1 example data, then pivot and clean it in preparation for merging with the other two selected sample files.

For your submission you will adjust the code to reflect your selected dataset.

In [6]:
data1 = pd.read_csv(data_file_1)
data1.head()

                  date datatype            station attributes  value
0  2018-10-01T00:00:00     TAVG  GHCND:USW00014732      H,,S,   21.2
1  2018-10-01T00:00:00     TMAX  GHCND:USW00014732   ,,W,2400   25.6
2  2018-10-01T00:00:00     TMIN  GHCND:USW00014732   ,,W,2400   18.3
3  2018-10-02T00:00:00     TAVG  GHCND:USW00014732      H,,S,   22.7
4  2018-10-02T00:00:00     TMAX  GHCND:USW00014732   ,,W,2400   26.1

In [20]:
data1_wide = data1.pivot_table(
    index=["date", "station"],
    columns="datatype",
    values="value",
    aggfunc="first"
).reset_index()

data1_wide.columns.name = None
data1_wide.head()

                  date            station  TAVG  TMAX  TMIN
0  2018-10-01T00:00:00  GHCND:USW00014732  21.2  25.6  18.3
1  2018-10-02T00:00:00  GHCND:USW00014732  22.7  26.1  19.4
2  2018-10-03T00:00:00  GHCND:USW00014732  21.8  25.0  18.9
3  2018-10-04T00:00:00  GHCND:USW00014732  21.3  26.1  17.8
4  2018-10-05T00:00:00  GHCND:USW00014732  20.3  22.8  16.1

In [32]:
data1_wide["date"] = pd.to_datetime(data1_wide["date"])

data1_wide.dtypes

numeric_columns = data1_wide.select_dtypes(
    include="number"
).columns

data1_wide[numeric_columns] = (
    data1_wide[numeric_columns].fillna(0)
)

data1_wide.head()

        date            station  TAVG  TMAX  TMIN
0 2018-10-01  GHCND:USW00014732  21.2  25.6  18.3
1 2018-10-02  GHCND:USW00014732  22.7  26.1  19.4
2 2018-10-03  GHCND:USW00014732  21.8  25.0  18.9
3 2018-10-04  GHCND:USW00014732  21.3  26.1  17.8
4 2018-10-05  GHCND:USW00014732  20.3  22.8  16.1

In [33]:
data1_wide.info()
data1_wide.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     31 non-null     datetime64[ns]
 1   station  31 non-null     object
 2   TAVG     31 non-null     float64
 3   TMAX     31 non-null     float64
 4   TMIN     31 non-null     float64
dtypes: datetime64[ns](1), float64(3), object(1)
memory usage: 1.3+ KB

        date            station  TAVG  TMAX  TMIN
0 2018-10-01  GHCND:USW00014732  21.2  25.6  18.3
1 2018-10-02  GHCND:USW00014732  22.7  26.1  19.4
2 2018-10-03  GHCND:USW00014732  21.8  25.0  18.9
3 2018-10-04  GHCND:USW00014732  21.3  26.1  17.8
4 2018-10-05  GHCND:USW00014732  20.3  22.8  16.1

### Data File 2 dataframe
Here we will load the data_file_2 example data, then pivot and clean it in preparation for merging with the other two selected sample files.

For your submission you will adjust the code to reflect your selected dataset.

In [39]:
data2 = pd.read_csv(data_file_2)
data2.head()

                  date datatype            station attributes  value
0  2018-01-01T00:00:00     PRCP  GHCND:US1CTFR0039       ,,N,    0.0
1  2018-01-01T00:00:00     PRCP  GHCND:US1NJBG0015       ,,N,    0.0
2  2018-01-01T00:00:00     SNOW  GHCND:US1NJBG0015       ,,N,    0.0
3  2018-01-01T00:00:00     PRCP  GHCND:US1NJBG0017       ,,N,    0.0
4  2018-01-01T00:00:00     SNOW  GHCND:US1NJBG0017       ,,N,    0.0

In [43]:
data2["date"] = pd.to_datetime(data2["date"])
data2.dtypes

data2_wide = data2.pivot_table(
    index=["date", "station"],
    columns="datatype",
    values="value",
    aggfunc="first"
).reset_index()

In [47]:
data2_wide.columns.name = None
data2_wide.head()

data2_wide.dropna(
    axis=1,
    how="all",
    inplace=True
)

data2_wide.head()

numeric_columns = data2_wide.select_dtypes(
    include="number"
).columns

data2_wide[numeric_columns] = (
    data2_wide[numeric_columns].fillna(0)
)

data2_wide.head()

,date,station,AWND,DAPR,MDPR,PGTM,PRCP,SNOW,SNWD,TAVG,...,WSF5,WT01,WT02,WT03,WT04,WT05,WT06,WT08,WT09,WT11
0,2018-01-01,GHCND:US1CTFR0039,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2018-01-01,GHCND:US1NJBG0015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018-01-01,GHCND:US1NJBG0017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2018-01-01,GHCND:US1NJBG0018,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2018-01-01,GHCND:US1NJBG0023,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [48]:
data2_wide.info()
data2_wide.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27835 entries, 0 to 27834
Data columns (total 29 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     27835 non-null  datetime64[ns]
 1   station  27835 non-null  object
 2   AWND     27835 non-null  float64
 3   DAPR     27835 non-null  float64
 4   MDPR     27835 non-null  float64
 5   PGTM     27835 non-null  float64
 6   PRCP     27835 non-null  float64
 7   SNOW     27835 non-null  float64
 8   SNWD     27835 non-null  float64
 9   TAVG     27835 non-null  float64
 10  TMAX     27835 non-null  float64
 11  TMIN     27835 non-null  float64
 12  TOBS     27835 non-null  float64
 13  TSUN     27835 non-null  float64
 14  WDF2     27835 non-null  float64
 15  WDF5     27835 non-null  float64
 16  WESD     27835 non-null  float64
 17  WESF     27835 non-null  float64
 18  WSF2     27835 non-null  float64
 19  WSF5     27835 non-null  float64
 20  WT01     27835 non-null  float64
 21  WT02     27835 non-null  float64
 22  WT03     27835 non-null  float64
 23  WT04     27835 non-null  float64
 24  WT05     27835 non-null  float64
 25  WT06     27835 non-null  float64
 26  WT08     27835 non-null  float64
 27  WT09     27835 non-null  float64
 28  WT11     27835 non-null  float64
dtypes: datetime64[ns](1), float64(27), object(1)
memory usage: 6.2+ MB

,date,station,AWND,DAPR,MDPR,PGTM,PRCP,SNOW,SNWD,TAVG,...,WSF5,WT01,WT02,WT03,WT04,WT05,WT06,WT08,WT09,WT11
0,2018-01-01,GHCND:US1CTFR0039,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2018-01-01,GHCND:US1NJBG0015,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018-01-01,GHCND:US1NJBG0017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2018-01-01,GHCND:US1NJBG0018,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2018-01-01,GHCND:US1NJBG0023,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Data Merging
Here is the example of a merge of the three sample files. You will need to adjust these blocks for how you wish to merge your selected data files.

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you need merge your dataset.</span>
</div>

In [49]:
merged_data_1_2 = pd.merge(
    data1_wide,
    data2_wide,
    on=["date", "station"],
    how="inner",
    suffixes=("_data1", "_data2")
)

merged_data_1_2

,date,station,TAVG_data1,TMAX_data1,TMIN_data1,AWND,DAPR,MDPR,PGTM,PRCP,...,WSF5,WT01,WT02,WT03,WT04,WT05,WT06,WT08,WT09,WT11
0,2018-10-01,GHCND:USW00014732,21.2,25.6,18.3,3.1,0.0,0.0,0.0,0.0,...,9.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2018-10-02,GHCND:USW00014732,22.7,26.1,19.4,4.3,0.0,0.0,0.0,14.2,...,12.5,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018-10-03,GHCND:USW00014732,21.8,25.0,18.9,3.6,0.0,0.0,0.0,0.0,...,9.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2018-10-04,GHCND:USW00014732,21.3,26.1,17.8,2.5,0.0,0.0,0.0,1.0,...,8.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2018-10-05,GHCND:USW00014732,20.3,22.8,16.1,4.3,0.0,0.0,0.0,0.0,...,12.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2018-10-06,GHCND:USW00014732,18.7,21.1,17.8,3.6,0.0,0.0,0.0,0.0,...,8.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2018-10-07,GHCND:USW00014732,22.8,27.8,21.1,2.3,0.0,0.0,0.0,0.0,...,7.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2018-10-08,GHCND:USW00014732,20.9,22.8,18.3,4.5,0.0,0.0,0.0,0.0,...,8.5,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,2018-10-09,GHCND:USW00014732,21.8,25.6,19.4,3.3,0.0,0.0,0.0,0.0,...,7.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2018-10-10,GHCND:USW00014732,23.8,27.8,21.7,3.5,0.0,0.0,0.0,0.0,...,8.9,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2018-10-11,GHCND:USW00014732,23.4,26.7,21.7,3.6,0.0,0.0,0.0,16.0,...,13.4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2018-10-12,GHCND:USW00014732,18.3,22.2,12.2,7.7,0.0,0.0,0.0,13.2,...,16.1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2018-10-13,GHCND:USW00014732,12.2,15.0,9.4,4.7,0.0,0.0,0.0,1.3,...,10.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2018-10-14,GHCND:USW00014732,12.9,15.6,10.6,3.0,0.0,0.0,0.0,0.0,...,7.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2018-10-15,GHCND:USW00014732,15.8,21.1,12.8,4.9,0.0,0.0,0.0,1.0,...,18.3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2018-10-16,GHCND:USW00014732,14.3,16.7,9.4,5.8,0.0,0.0,0.0,0.5,...,17.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2018-10-17,GHCND:USW00014732,13.2,17.8,8.9,7.2,0.0,0.0,0.0,0.0,...,16.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2018-10-18,GHCND:USW00014732,9.6,11.7,6.7,6.6,0.0,0.0,0.0,0.0,...,15.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2018-10-19,GHCND:USW00014732,11.3,17.2,7.2,4.9,0.0,0.0,0.0,0.0,...,13.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2018-10-20,GHCND:USW00014732,15.0,18.3,12.2,5.2,0.0,0.0,0.0,1.8,...,12.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2018-10-21,GHCND:USW00014732,10.7,12.2,6.1,8.2,0.0,0.0,0.0,0.0,...,19.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2018-10-22,GHCND:USW00014732,8.3,11.1,5.6,4.3,0.0,0.0,0.0,0.0,...,9.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2018-10-23,GHCND:USW00014732,12.6,19.4,8.3,4.8,0.0,0.0,0.0,0.0,...,14.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,2018-10-24,GHCND:USW00014732,11.0,13.3,7.8,8.1,0.0,0.0,0.0,0.0,...,15.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,2018-10-25,GHCND:USW00014732,8.8,11.1,6.1,6.6,0.0,0.0,0.0,0.0,...,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2018-10-26,GHCND:USW00014732,7.3,10.0,5.6,3.4,0.0,0.0,0.0,0.0,...,10.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,2018-10-27,GHCND:USW00014732,9.4,11.7,7.2,10.0,0.0,0.0,0.0,25.7,...,22.4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,2018-10-28,GHCND:USW00014732,10.2,12.2,8.3,4.2,0.0,0.0,0.0,1.3,...,9.4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2018-10-29,GHCND:USW00014732,11.8,14.4,9.4,5.7,0.0,0.0,0.0,0.8,...,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2018-10-30,GHCND:USW00014732,10.2,13.9,7.2,5.6,0.0,0.0,0.0,0.0,...,12.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,2018-10-31,GHCND:USW00014732,12.6,17.8,7.2,3.6,0.0,0.0,0.0,0.0,...,12.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
final_merged_data = pd.merge(
    data1_wide,
    data2_wide,
    on=["date", "station"],
    how="inner",
    suffixes=("_data1", "_data2")
)

final_merged_data.info()
final_merged_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        31 non-null     datetime64[ns]
 1   station     31 non-null     object
 2   TAVG_data1  31 non-null     float64
 3   TMAX_data1  31 non-null     float64
 4   TMIN_data1  31 non-null     float64
 5   AWND        31 non-null     float64
 6   DAPR        31 non-null     float64
 7   MDPR        31 non-null     float64
 8   PGTM        31 non-null     float64
 9   PRCP        31 non-null     float64
 10  SNOW        31 non-null     float64
 11  SNWD        31 non-null     float64
 12  TAVG_data2  31 non-null     float64
 13  TMAX_data2  31 non-null     float64
 14  TMIN_data2  31 non-null     float64
 15  TOBS        31 non-null     float64
 16  TSUN        31 non-null     float64
 17  WDF2        31 non-null     float64
 18  WDF5        31 non-null     float64
 19  WESD        31 non-null     float64
 20  WESF        31 non-null     float64
 21  WSF2        31 non-null     float64
 22  WSF5        31 non-null     float64
 23  WT01        31 non-null     float64
 24  WT02        31 non-null     float64
 25  WT03        31 non-null     float64
 26  WT04        31 non-null     float64
 27  WT05        31 non-null     float64
 28  WT06        31 non-null     float64
 29  WT08        31 non-null     float64
 30  WT09        31 non-null     float64
 31  WT11        31 non-null     float64
dtypes: datetime64[ns](1), float64(30), object(1)
memory usage: 7.9+ KB

,date,station,TAVG_data1,TMAX_data1,TMIN_data1,AWND,DAPR,MDPR,PGTM,PRCP,...,WSF5,WT01,WT02,WT03,WT04,WT05,WT06,WT08,WT09,WT11
0,2018-10-01,GHCND:USW00014732,21.2,25.6,18.3,3.1,0.0,0.0,0.0,0.0,...,9.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2018-10-02,GHCND:USW00014732,22.7,26.1,19.4,4.3,0.0,0.0,0.0,14.2,...,12.5,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018-10-03,GHCND:USW00014732,21.8,25.0,18.9,3.6,0.0,0.0,0.0,0.0,...,9.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2018-10-04,GHCND:USW00014732,21.3,26.1,17.8,2.5,0.0,0.0,0.0,1.0,...,8.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2018-10-05,GHCND:USW00014732,20.3,22.8,16.1,4.3,0.0,0.0,0.0,0.0,...,12.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Data Output

<div class="alert alert-block alert-danger">
    <span style="color:black"><b><i>Example Data:</i></b> Keep in mind that the output below are from the sample data and will need replaced before running the block with your dataset for how you want to output your merged dataset.</span>
</div>

<div class="alert alert-block alert-success">
    <span style="color:black"><b><i>Data Output:</i></b> replace the output path <b><mark>'data/sample_use_only/sample_output/sample_merged_data.csv'</mark></b> with your path <b><mark>'data/{your_merged_data.csv}'</mark></b>.</span>
</div>

In [53]:
final_merged_data.to_csv('data/final_merged_data.csv')